//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientChapterv2_Michael
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientChapter
    {
        public int ClientChapterSKey { get; set; }
        public string chapter { get; set; }
        public string tstate { get; set; }
        public string chap_name { get; set; }
        public string iid { get; set; }
        public string area_name { get; set; }
        public string env1 { get; set; }
        public string env2 { get; set; }
        public string env3 { get; set; }
        public string env4 { get; set; }
        public string tname { get; set; }
        public string taddr1 { get; set; }
        public string taddr2 { get; set; }
        public string taddr3 { get; set; }
        public string tcity { get; set; }
        public string tzip { get; set; }
        public string whokey { get; set; }
        public string tran_date { get; set; }
        public string uw { get; set; }
        public string commander { get; set; }
        public string comm_title { get; set; }
        public string cid { get; set; }
        public string ctype { get; set; }
        public string billchap { get; set; }
        public string comm_lname { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string oldchap { get; set; }
        public string memo { get; set; }
        public string cust_no { get; set; }
        public string invchap { get; set; }
        public string nl_tag { get; set; }
        public string origcid { get; set; }
        public string origiid { get; set; }
        public string webadd { get; set; }
        public string region { get; set; }
        public string lockbox { get; set; }
        public string uwblackfm { get; set; }
        public string uwblackto { get; set; }
        public string md_coord { get; set; }
        public string commander2 { get; set; }
        public string commtitle2 { get; set; }
        public string commlname2 { get; set; }
        public string billchap2 { get; set; }
        public string email2 { get; set; }
        public string mspthanks { get; set; }
        public string lastthank { get; set; }
        public string seedname { get; set; }
        public string env5 { get; set; }
        public string origname { get; set; }
        public string clientname { get; set; }
        public string chapdesig { get; set; }
        public string division { get; set; }
        public string active { get; set; }
        public string site_id { get; set; }
        public string tsm_enters { get; set; }
        public string envcity { get; set; }
        public string envstate { get; set; }
        public string envzip { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    }
}
